---
- name: Configure python
  hosts: localhost
  connection: local

  tasks:
    - name: Upgrade pip
      ansible.builtin.pip: # noqa package-latest
        name: pip
        state: latest
      tags:
        - python
        - pip

    - name: Install important pip packages
      ansible.builtin.pip: # noqa package-latest
        state: latest
        extra_args: --user
        name:
          - ansible
          - ansible-lint
          - ansible-navigator
          - asciinema
          - c7n
          - c7n_azure
          - c7n_gcp
          - checkov
          - j2cli[yaml]
          - pipenv
          - pre-commit
          - pyyaml
          - romt
      tags:
        - python
        - pip
