---
- name: Configure Rust
  hosts: localhost
  connection: local

  tasks:
    - name: Check if Rust tools are installed
      ansible.builtin.command:
        cmd: which rustup
      register: rustup_exists
      changed_when: false
      ignore_errors: true
      tags:
        - rust

    - name: Download and install rustup
      when: 1 == rustup_exists.rc
      tags:
        - rust
      block:
        - name: Download rustup
          ansible.builtin.get_url:
            dest: /tmp/install-rustup
            owner: "{{ username }}"
            mode: u=rwx,g=r,o=r
            url: https://sh.rustup.rs

        - name: Install Rust
          ansible.builtin.command:
            cmd: /tmp/install-rustup -y
          args:
            creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"

        - name: Remove install script
          ansible.builtin.file:
            path: /tmp/install-rustup
            state: absent
            force: true

    - name: Add necessary components
      ansible.builtin.command:
        argv:
          - "{{ lookup('env', 'HOME') }}/.cargo/bin/rustup"
          - component
          - add
          - cargo
          - clippy
          - rls
          - rust-analysis
          - rust-docs
          - rust-src
          - rust-std
          - rustc
          - rustfmt
      changed_when: false
      tags:
        - rust

    - name: Install Cargo tools
      ansible.builtin.command:
        argv:
          - "{{ lookup('env', 'HOME') }}/.cargo/bin/cargo"
          - install
          - --force
          - cargo-tarpaulin
          - cargo-make
          - sccache
      changed_when: false
