---
- name: "Everything and the kitchen sink"
  hosts: localhost
  connection: local

  tasks:
    - name: Include OS variables
      ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.vars.yaml"

    - name: Bootstrap OS
      ansible.builtin.include_tasks: "{{ ansible_facts.os_family }}.ansible.yaml"
      tags:
        - bootstrap

    - name: Ensure user is configured properly
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ username }}"
        shell: "/usr/bin/zsh"
      become: true

    - name: Generate local ed25519 key
      community.crypto.openssh_keypair:
        owner: "{{ username }}"
        group: "{{ username }}"
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
        comment: "{{ username }}@{{ ansible_facts.hostname }}"
        type: ed25519

    - name: Generate local RSA key
      community.crypto.openssh_keypair:
        owner: "{{ username }}"
        group: "{{ username }}"
        path: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
        comment: "{{ username }}@{{ ansible_facts.hostname }}"
        type: rsa
        size: 4096
