---
- name: "Everything and the kitchen sink"
  hosts: localhost
  connection: local

  tasks:
    - name: Include OS variables
      ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.vars.yaml"

    - name: Bootstrap OS
      ansible.builtin.include_tasks: "{{ ansible_facts.os_family }}.ansible.yaml"
      tags:
        - bootstrap

    - name: Ensure user is configured properly
      ansible.builtin.user:
        name: "{{ username }}"
        group: "{{ username }}"
        shell: "/bin/zsh"
      become: true
