---
- name: "Everything and the kitchen sink"
  hosts: localhost
  connection: localhost

  tasks:
    - name: "Test ansible"
      ansible.builtin.debug:
        var: ansible_facts

    - name: "Testing library"
      yay:
        update_cache: true
