---
- name: "Everything and the kitchen sink"
  hosts: localhost
  connection: local

  tasks:
    - name: Include OS variables
      ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.vars.yaml"

    - name: Bootstrap OS
      ansible.builtin.include_tasks: "{{ ansible_facts.os_family }}.ansible.yaml"
      tags:
        - bootstrap

    - name: Configure user
      ansible.builtin.include_tasks: user.ansible.yaml
      tags:
        - user

    - name: Configure date and time
      ansible.builtin.include_tasks: datetime.ansible.yaml
      tags:
        - datetime

    - name: Configure Python
      ansible.builtin.include_tasks: python.ansible.yaml
      tags:
        - python

    - name: Configure Rust
      ansible.builtin.include_tasks: rust.ansible.yaml
      tags:
        - rust

    - name: Configure zsh
      ansible.builtin.include_tasks: zsh.ansible.yaml
      tags:
        - zsh
