---
- name: "Everything and the kitchen sink"
  hosts: localhost
  connection: local

  tasks:
    - name: Include OS variables
      ansible.builtin.include_vars: "{{ ansible_facts.os_family }}.vars.yaml"

    - name: Bootstrap OS
      ansible.builtin.include_tasks: "{{ ansible_facts.os_family }}.ansible.yaml"
      tags:
        - bootstrap

- name: Configure user
  ansible.builtin.import_playbook: user.ansible.yaml
  tags:
    - user

- name: Configure date and time
  ansible.builtin.import_playbook: datetime.ansible.yaml
  tags:
    - datetime

- name: Configure Python
  ansible.builtin.import_playbook: python.ansible.yaml
  tags:
    - python

- name: Configure Rust
  ansible.builtin.import_playbook: rust.ansible.yaml
  tags:
    - rust

- name: Configure zsh
  ansible.builtin.import_playbook: zsh.ansible.yaml
  tags:
    - zsh

- name: Configure GitHub
  ansible.builtin.import_playbook: github.ansible.yaml
  tags:
    - github

- name: Set up YADM
  ansible.builtin.import_playbook: yadm.ansible.yaml
  tags:
    - yadm
