---
- name: Configure zsh
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure plugins directory exists
      ansible.builtin.file:
        state: directory
        path: "{{ lookup('env', 'HOME') }}/.config/zsh/plugins"
        owner: "{{ username }}"
        group: "{{ username }}"
      tags:
        - zsh

    - name: Install zsh-autocomplete
      ansible.builtin.git: # noqa latest
        recursive: true
        reference: main
        repo: https://github.com/marlonrichert/zsh-autocomplete.git
        single_branch: true
        update: true
      tags:
        - zsh
