---
- name: Configure zsh
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure plugins directory exists
      ansible.builtin.file:
        state: directory
        path: "{{ lookup('env', 'HOME') }}/.config/zsh/plugins"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: u=rwx,g=rx,o=rx
      register: zsh_plugins
      tags:
        - zsh

    - name: Install zsh-autocomplete
      ansible.builtin.git: # noqa latest
        recursive: true
        version: main
        repo: https://github.com/marlonrichert/zsh-autocomplete.git
        single_branch: true
        update: true
        dest: "{{ zsh_plugins.path }}/zsh-autocomplete"
      tags:
        - zsh

    - name: Install zsh-syntax-highlighting
      ansible.builtin.git: # noqa latest
        recursive: true
        version: master
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        single_branch: true
        update: true
        dest: "{{ zsh_plugins.path }}/zsh-syntax-highlighting"
